### ISSUE TITLE
what copyright issues prevent these frome being in the official market?

### ISSUE THREAD

**Issue by lilkidsuave** [TinyActive/cosmos-servapps#4]

**Comment by vncloudsco** [comment]
Thank you for your question, I will clarify it here:
- Some software is under the management of companies and it needs a license to use like Synology, Atlassian, Acunetix, we unfortunately do not have a license to combine it with other software.
- Some software does not have security risks if you do not know what they are because the software itself contains security vulnerabilities eg: Webgoat..... 
- In addition, we support open source software to help maintain the application market to avoid being closed through DMCA.

For the above reasons, we only provide it as a 3rd party app market to avoid affecting users. Thank you for your interest. If you have further questions, please let me know
